CREATE DATABASE IF NOT EXISTS rentalku; USE rentalku;
CREATE TABLE mobil (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,nama_mobil VARCHAR(100),merk VARCHAR(100),tahun YEAR,plat_nomor VARCHAR(20) UNIQUE,harga_sewa DECIMAL(12,2),status ENUM('Tersedia','Disewa','Perawatan') DEFAULT 'Tersedia',created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL);
CREATE TABLE pelanggan (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,nama VARCHAR(100),alamat TEXT,no_hp VARCHAR(20),no_ktp VARCHAR(20) UNIQUE,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL);
